### ISSUE TITLE
matlab libraries linking problem

### ISSUE THREAD

**Issue by josephdviviano** [josephdviviano/epitome#38]
on init_basic

**\* MODULE: init_basic. Reorients, phys regression, removes init TRs. ***
++ 3dcalc: AFNI version=AFNI_2011_12_21_1014 (Dec 10 2014) [64-bit]
++ Authored by: A cast of thousands

++ VERSION CHECK!  This program = AFNI_2011_12_21_1014
++         Current AFNI website = AFNI_16.0.00
## Setting up environment variables

LD_LIBRARY_PATH is .:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2013b/runtime/glnxa64:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2013b/bin/glnxa64:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2013b/sys/os/glnxa64:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2013b/sys/java/jre/glnxa64/jre/lib/amd64/native_threads:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2013b/sys/java/jre/glnxa64/jre/lib/amd64/server:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2013b/sys/java/jre/glnxa64/jre/lib/amd64/client:/opt/quarantine/matlab/matlab_concurrent_all/MATLAB_R2013b/sys/java/jre/glnxa64/jre/lib/amd64
/home/colin/epitome/tms_part1/bin/McRetroTS: error while loading shared libraries: libmwmclmcrrt.so.7.15: cannot open shared object file: No such file or directory

**Comment by josephdviviano** [comment]
This was a bug in erin's branch of the code -- no longer an issue.

**Comment by hodaelcohen** [comment]
how you fix that?????  i have the same problem 
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to find the required library libmwmclmcrrt.so.9.6 on java.library.path.
This library is typically installed along with MATLAB or the MATLAB Runtime. Its absence may indicate an issue with that installation or 
the current path configuration, or a mismatch with the architecture of the Java interpreter on the path.
MATLAB Runtime version this component is attempting to use: 9.6.
Java interpreter architecture: glnxa64.

	at com.mathworks.toolbox.javabuilder.internal.MCRConfiguration$ProxyLibraryDir.get(MCRConfiguration.java:185)
	at com.mathworks.toolbox.javabuilder.internal.MCRConfiguration$ProxyLibraryDir.<clinit>(MCRConfiguration.java:195)
	at com.mathworks.toolbox.javabuilder.internal.MCRConfiguration.getProxyLibraryDir(MCRConfiguration.java:200)
	at com.mathworks.toolbox.javabuilder.internal.MCRConfiguration$MCRRoot.get(MCRConfiguration.java:64)
	at com.mathworks.toolbox.javabuilder.internal.MCRConfiguration$MCRRoot.<clinit>(MCRConfiguration.java:76)
	at com.mathworks.toolbox.javabuilder.internal.MCRConfiguration.getMCRRoot(MCRConfiguration.java:81)
	at com.mathworks.toolbox.javabuilder.internal.MCRConfiguration$ModuleDir.<clinit>(MCRConfiguration.java:53)
	at com.mathworks.toolbox.javabuilder.internal.MCRConfiguration.getModuleDir(MCRConfiguration.java:58)
	at com.mathworks.toolbox.javabuilder.internal.MWMCR.<clinit>(MWMCR.java:1711)
	at makesqr.MakesqrMCRFactory.newInstance(MakesqrMCRFactory.java:44)
	at makesqr.MakesqrMCRFactory.newInstance(MakesqrMCRFactory.java:55)
	at makesqr.Class1.<init>(Class1.java:62)
	at sqr.main(sqr.java:10)

**Comment by josephdviviano** [comment]
I don't know the details on your machine so I don't think I can help you.

This isn't the same issue, as you are reporting a missing `libmwmclmcrrt.so.9.6 on java.library.path`, i suspect it is a java installation / version issue.

**Comment by josephdviviano** [comment]
have a look here: https://www.mathworks.com/matlabcentral/answers/20124-missmatch-between-mcr-version-and-packaged-jar-failed-to-find-the-library-libmwmclmcrrt-so-7-13
