### ISSUE TITLE
Unable to run epitome on Sharcnet

### ISSUE THREAD

**Issue by jaegerl** [josephdviviano/epitome#50]
epitome run gives the following error:

Traceback (most recent call last):
  File "/work/grturner/sw/epitome/bin/epitome", line 16, in <module>
    import epitome as epi
  File "/work/grturner/sw/epitome/epitome/**init**.py", line 6, in <module>
    from . import config
  File "/work/grturner/sw/epitome/epitome/config.py", line 7, in <module>
    from epitome.utilities import get_date_user
  File "/work/grturner/sw/epitome/epitome/utilities.py", line 9, in <module>
    import nibabel as nib
ImportError: No module named nibabel

which epitome reads the following output:
/work/grturner/sw/epitome/bin/epitome

**Comment by josephdviviano** [comment]
Try installing nibabel http://nipy.org/nibabel/installation.html
