### ISSUE TITLE
fs-export won't run

### ISSUE THREAD

**Issue by colinhawco** [josephdviviano/epitome#51]
colin@golgi:/scratch/colin/epitome/SPINS$ epi-fsexport /scratch/colin/epitome/SPINS SPINS

Traceback (most recent call last):
  File "/projects/colin/applications/epitome/bin/epi-fsexport", line 119, in <module>
    main()
  File "/projects/colin/applications/epitome/bin/epi-fsexport", line 103, in main
    subjects = epi.utilities.get_subj(os.path.join(path, expt))
  File "/projects/colin/applications/epitome/epitome/utilities.py", line 128, in get_subj
    for subj in os.walk(dir).next()[1]:
StopIteration

Running an older epitome
/projects/colin/applications/epitome/bin/epitome

**Comment by josephdviviano** [comment]
this is the command:

`epi-fsexport /scratch/colin/epitome SPINS`

**Comment by josephdviviano** [comment]
This is no longer relevant to epitome.
