### ISSUE TITLE
:D

### ISSUE THREAD

**Issue by josephdviviano** [josephdviviano/epitome#9]
Saving master script & generating subject-specific scripts.
Traceback (most recent call last):
  File "/projects/anne/code/epitome/bin/epi-fsrecon", line 91, in <module>
    FS_recon(root, expt, mode, proc)
  File "/projects/anne/code/epitome/bin/epi-fsrecon", line 58, in FS_recon
    stack = generate_stack(root, expt)
  File "/projects/anne/code/epitome/bin/epi-fsrecon", line 44, in generate_stack
    if os.path.isdir(os.path.join(fs_dir, fs_subject)) == True:
NameError: global name 'fs_subject' is not defined
^C******************************************************************
The pipeline can be manually executed via:
. /projects/anne/current/epitome/PNC/proclist_150310_170650_pnc-1.sh
or submitted to the queue via:
epi-queue /projects/anne/current/epitome/PNC/proclist_150310_170650_pnc-1.sh

---

**Comment by josephdviviano** [comment]
variable naming error -- fixed.
